---
# Source: bluesky-pds/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bluesky-pds
  labels:
    app.kubernetes.io/name: bluesky-pds
    app.kubernetes.io/instance: bluesky-pds
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: pds-port
      protocol: TCP
      name: pds-port
  selector:
    app.kubernetes.io/name: bluesky-pds
    app.kubernetes.io/instance: bluesky-pds
---
# Source: bluesky-pds/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluesky-pds
  labels:
    app.kubernetes.io/name: bluesky-pds
    app.kubernetes.io/instance: bluesky-pds
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bluesky-pds
      app.kubernetes.io/instance: bluesky-pds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bluesky-pds
        app.kubernetes.io/instance: bluesky-pds
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: bluesky-pds
          securityContext:
            {}
          image: "ghcr.io/bluesky-social/pds:0.4.59"
          imagePullPolicy: IfNotPresent
          env:
            - name: PDS_HOSTNAME
              value: pds.bluesky.sindt.org
            - name: PDS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwtSecret
            - name: PDS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: adminPassword
            - name: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: plcRotationKey
            - name: PDS_EMAIL_SMTP_URL 
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: smtp 
            - name: PDS_EMAIL_FROM_ADDRESS 
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: email 
            - name: PDS_DATA_DIRECTORY
              value: "/pds"
            - name: PDS_BLOBSTORE_DISK_LOCATION
              value: "/pds/blocks"
            - name: PDS_DID_PLC_URL
              value: "https://plc.directory"
            - name: PDS_BSKY_APP_VIEW_URL
              value: "https://api.bsky.app"
            - name: PDS_BSKY_APP_VIEW_DID
              value: "did:web:api.bsky.app"
            - name: PDS_REPORT_SERVICE_URL
              value: "https://mod.bsky.app"
            - name: PDS_REPORT_SERVICE_DID
              value: "did:plc:ar7c4by46qjdydhdevvrndac"
            - name: PDS_CRAWLERS
              value: "https://bsky.network"
            - name: LOG_ENABLED
              value: "true"
          ports:
            - name: pds-port
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /pds
          livenessProbe:
            httpGet:
              path: /xrpc/_health
              port: pds-port
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {}
      volumes:
        - name: data
          hostPath:
            path: /ssd/k3s/bluesky/pds
            type: Directory
---
# Source: bluesky-pds/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluesky-pds
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: bluesky-pds
    app.kubernetes.io/instance: bluesky-pds
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "pds.bluesky.sindt.org"
      secretName: pds-bluesky-sindt-org-tls
  rules:
    - host: "pds.bluesky.sindt.org"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bluesky-pds
                port:
                  number: 3000
